CREATE TABLE PUBLIC.C_TIPO_AERONAVE (ID_TIPO_AERONAVE INT NOT NULL, DS_NOMBRE NVARCHAR(100) NOT NULL, DS_CODIGO NVARCHAR(5) NOT NULL, CONSTRAINT PK_C_TIPO_AERONAVE PRIMARY KEY (ID_TIPO_AERONAVE));

CREATE TABLE PUBLIC.C_AEROLINEA (ID_AEROLINEA INT NOT NULL, DS_NOMBRE NVARCHAR(100) NOT NULL, DS_CODIGO NVARCHAR(2) NOT NULL, CONSTRAINT PK_C_AEROLINEA PRIMARY KEY (ID_AEROLINEA));

CREATE TABLE PUBLIC.K_AERONAVE (ID_AERONAVE INT AUTO_INCREMENT NOT NULL, ID_AEROLINEA INT NOT NULL, ID_TIPO_AERONAVE INT NOT NULL, DS_MATRICULA NVARCHAR(10) NOT NULL, CONSTRAINT PK_K_AERONAVE PRIMARY KEY (ID_AERONAVE));

ALTER TABLE PUBLIC.K_AERONAVE ADD CONSTRAINT FK_K_AERONAVE_C_AEROLINEA FOREIGN KEY (ID_AEROLINEA) REFERENCES PUBLIC.C_AEROLINEA (ID_AEROLINEA) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE PUBLIC.K_AERONAVE ADD CONSTRAINT FK_K_AERONAVE_C_TIPO_AERONAVE FOREIGN KEY (ID_TIPO_AERONAVE) REFERENCES PUBLIC.C_TIPO_AERONAVE (ID_TIPO_AERONAVE) ON UPDATE NO ACTION ON DELETE NO ACTION;

CREATE TABLE PUBLIC.C_PAIS (ID_PAIS INT NOT NULL, DS_NOMBRE NVARCHAR(100) NOT NULL, DS_CODIGO NVARCHAR(2) NOT NULL, CONSTRAINT PK_C_PAIS PRIMARY KEY (ID_PAIS));

CREATE TABLE PUBLIC.C_ESTACION (ID_ESTACION INT NOT NULL, ID_PAIS INT NOT NULL, DS_NOMBRE NVARCHAR(100) NOT NULL, DS_CODIGO NVARCHAR(3) NOT NULL, CONSTRAINT PK_C_ESTACION PRIMARY KEY (ID_ESTACION));

ALTER TABLE PUBLIC.C_ESTACION ADD CONSTRAINT FK_C_ESTACION_C_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PUBLIC.C_PAIS (ID_PAIS) ON UPDATE NO ACTION ON DELETE NO ACTION;

CREATE TABLE PUBLIC.K_RUTA (ID_RUTA INT AUTO_INCREMENT NOT NULL, ID_ESTACION_DEP INT NOT NULL, ID_ESTACION_ARR INT NOT NULL, DS_CODE NVARCHAR(6) NOT NULL, CONSTRAINT PK_K_RUTA PRIMARY KEY (ID_RUTA));

ALTER TABLE PUBLIC.K_RUTA ADD CONSTRAINT FK_K_RUTA_C_ESTACION_DEP FOREIGN KEY (ID_ESTACION_DEP) REFERENCES PUBLIC.C_ESTACION (ID_ESTACION) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE PUBLIC.K_RUTA ADD CONSTRAINT FK_K_RUTA_C_ESTACION_ARR FOREIGN KEY (ID_ESTACION_ARR) REFERENCES PUBLIC.C_ESTACION (ID_ESTACION) ON UPDATE NO ACTION ON DELETE NO ACTION;

CREATE TABLE PUBLIC.K_VUELO (ID_VUELO INT AUTO_INCREMENT NOT NULL, ID_AERONAVE INT NOT NULL, ID_RUTA INT NOT NULL, QT_VUELO INT NOT NULL, DT_SCH_DEPARTURE_UTC TIMESTAMP, DT_ACT_DEPARTURE_UTC TIMESTAMP, DT_SCH_ARRIVE_UTC TIMESTAMP, DT_ACT_ARRIVE_UTC TIMESTAMP, QT_TIME_DELAY_DEP INT DEFAULT 0 NOT NULL, QT_TIME_DELAY_ARR INT DEFAULT 0 NOT NULL, CONSTRAINT PK_K_VUELO PRIMARY KEY (ID_VUELO));

ALTER TABLE PUBLIC.K_VUELO ADD CONSTRAINT FK_K_VUELO_K_AERONAVE FOREIGN KEY (ID_AERONAVE) REFERENCES PUBLIC.K_AERONAVE (ID_AERONAVE) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE PUBLIC.K_VUELO ADD CONSTRAINT FK_K_VUELO_K_RUTA FOREIGN KEY (ID_RUTA) REFERENCES PUBLIC.K_RUTA (ID_RUTA) ON UPDATE NO ACTION ON DELETE NO ACTION;
